import { ExternalLink, FileText } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent } from '@/components/ui/card';

interface OriginalSourceLinkProps {
  sourceUrl: string;
  sourceName: string;
}

export function OriginalSourceLink({ sourceUrl, sourceName }: OriginalSourceLinkProps) {
  return (
    <Card className="bg-muted/30 border-border/50">
      <CardContent className="p-6">
        <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-full bg-muted flex items-center justify-center">
              <FileText className="h-5 w-5 text-muted-foreground" />
            </div>
            <div>
              <p className="text-sm text-muted-foreground">Original Source</p>
              <p className="font-medium text-foreground">{sourceName}</p>
            </div>
          </div>
          <Button
            variant="outline"
            asChild
            className="gap-2"
          >
            <a 
              href={sourceUrl} 
              target="_blank" 
              rel="noopener noreferrer"
            >
              <ExternalLink className="h-4 w-4" />
              Read Original Article
            </a>
          </Button>
        </div>
        <p className="text-xs text-muted-foreground mt-4 text-center sm:text-left">
          This analysis was generated by AI based on the original article. 
          Click above to view the source material.
        </p>
      </CardContent>
    </Card>
  );
}
